### PR TITLE
Support universal wheels

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by kennethreitz** [comment]
this actually isn't neccessary

**Comment by graingert** [comment]
@kennethreitz sure you can set it with `--universal` but this file is also recommended by the PyPA

**Comment by adamchainz** [comment]
@graingert you'd also need to update 'publish' in `setup.py` to call `bdist_wheel` https://github.com/kennethreitz/clint/blob/master/setup.py#L16

**Comment by techtonik** [comment]
Without wheels `clint` installation is covered in blood by AppVeyor https://ci.appveyor.com/project/spderosso/gitless/build/1.0.4/job/8nu7smkbbgbebo2k#L63

**Pull request merged**
