### PR TITLE
Issue#145 textui.prompt.yn

### PR DESCRIPTION
**Pull request by tz70s**
issue [#145](https://github.com/kennethreitz/clint/issues/145)
Hello , I'm not sure about what author exactly wanted this function do
However , I try to fixed the boolean return value in ```textui.prompt.yn() ```function
I agree ```issue #145``` concerned about the output is more close to users' thoughts
Testing  code as ```issue #145```
```Python
from clint.textui import prompt

for d in range(3):
    print(prompt.yn("Yes?"))

for y in range(3):
    print(prompt.yn("Yes? default=y", default="y"))

for n in range(3):
    print(prompt.yn("Yes? default=n", default="n"))
```
* Before , output changed when ```no``` as default section
```Python
Yes? default=n [y/N] y
False
Yes? default=n [y/N] n
True
Yes? default=n [y/N]
False
```
* After
```Python
Yes? default=n [y/N] y
True
Yes? default=n [y/N] n
False
Yes? default=n [y/N] 
False
```
* The ```yn``` function's return value is now defined as
```Python
yes  ->  return True
```
```Python
no   ->  return False
```
```Python
NULL string -> return True if default is 'y' else False
 ```

### CODE REVIEW

**Comment by wkentaro** [comment]
lgtm. :+1:

**Comment by wkentaro** [comment]
two commits can be squashed?

**Comment by tz70s** [comment]
Sure, I'll do it later

**Comment by wkentaro** [comment]
maybe you need another rebase.

**Comment by tz70s** [comment]
Sorry, I got messed on rebase. I can get an another pr if needed.

**Pull request closed without merging**
